name: 'SockBoom Checkin Action'

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: '0 16 * * *'
  watch:
    types: [started]
   
jobs:
  checking:
    runs-on: ubuntu-latest
    env:
      DOMAIN: https://sockboom.tv
    if: github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule'
    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai          
    - name: Get log
      uses: actions/checkout@master
    - name: login in APi #登录获取cookie
      env:
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: | 
        curl -s -c cookie.txt -X POST "$DOMAIN/auth/login" -d email="$EMAIL" -d passwd="$PASSWORD"
    - name: Chick in Api #签到
      env:
        WXPUSHERTOKEN: ${{ secrets.WXPUSHERTOKEN }}
      run: | 
        dateTime=`date +%Y-%m-%d\ %H:%M:%S`
        response=$(curl -b cookie.txt -X POST "$DOMAIN/user/checkin")
        curl 'http://wxpusher.zjiecode.com/api/send/message' -H 'Content-Type: application/json' -d '{"content": "$response","appToken": "'$WXPUSHERTOKEN'","uids":["UID_ZiVLTNi2xpezjcls0GKyEa5NJnUS"],"contentType":2}'
        echo "$dateTime - $(echo -e $response)" >> run.log
        tail run.log #避免日志上传失败丢失日志
    - name: Commit #上传日志到仓库，可以自行修改 name 和 email
      env:
       NAME: LeeYuze
       EMAIL: qw110288qw@vip.qq.com
      run: |
        git config --global user.name "$NAME"
        git config --global user.email "$EMAIL"
        git add .
        git commit -m "update log" -a
    - name: Push log
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
